---
url: https://lesliebeesleylmsw.github.io
baseurl: ''
compass:
  logo: "/images/officetree.png"
  author: Leslie Beesley, LMSW
  tagline: Clinical Social Work/Therapist
  tagline2: Adults · Children · Family
  description: 
  include_content: true
  include_analytics: false
markdown: kramdown
highlighter: rouge
permalink: pretty
