---
url: https://lesliebeesleylmsw.github.io
baseurl: ''
compass:
  logo: "/images/logo-sm.png"
  author: Leslie Beesley, LMSW
  tagline: Clinical Social Work/Therapist
  tagline2: Adults · Children · Family
  description: 
  meta_title: Trauma, Grief, Parenting Therapist - Lawrence KS - Leslie Beesley,LMSW
  include_content: true
  include_analytics: true
markdown: kramdown
highlighter: rouge
permalink: pretty
